package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// geometry_method_generator -geometryType BoxGeometry -geometrySlug box_geometry

import "github.com/gopherjs/gopherjs/js"
	
func (g BoxGeometry) ApplyMatrix(matrix *Matrix4) {
	g.Object.Call("applyMatrix", matrix)
}

func (g BoxGeometry) RotateX() {
	g.Object.Call("rotateX")
}

func (g BoxGeometry) RotateY() {
	g.Object.Call("rotateY")
}

func (g BoxGeometry) RotateZ() {
	g.Object.Call("rotateZ")
}

func (g BoxGeometry) Translate() {
	g.Object.Call("translate")
}

func (g BoxGeometry) Scale() {
	g.Object.Call("scale")
}

func (g BoxGeometry) LookAt() {
	g.Object.Call("lookAt")
}

func (g BoxGeometry) FromBufferGeometry(geometry Geometry) {
	g.Object.Call("fromBufferGeometry")
}

func (g BoxGeometry) Center() {
	g.Object.Call("center")
}

func (g BoxGeometry) Normalize() BoxGeometry {
	g.Object.Call("normalize")
	return g
}

func (g BoxGeometry) ComputeFaceNormals() {
	g.Object.Call("computeFaceNormals")
}

func (g BoxGeometry) ComputeVertexNormals(areaWeighted bool) {
	g.Object.Call("computeVertexNormals", areaWeighted)
}

func (g BoxGeometry) ComputeFlatVertexNormals() {
	g.Object.Call("computeFlatVertexNormals")
}

func (g BoxGeometry) ComputeMorphNormals() {
	g.Object.Call("computeMorphNormals")
}

func (g BoxGeometry) ComputeLineDistances() {
	g.Object.Call("computeLineDistances")
}

func (g BoxGeometry) ComputeBoundingBox() {
	g.Object.Call("computeBoundingBox")
}

func (g BoxGeometry) ComputeBoundingSphere() {
	g.Object.Call("computeBoundingSphere")
}

func (g BoxGeometry) Merge(geometry Geometry, matrix Matrix4, materialIndexOffset float64) {
	g.Object.Call("merge", geometry, matrix, materialIndexOffset)
}

func (g BoxGeometry) MergeMesh(mesh Mesh) {
	g.Object.Call("mergeMesh", mesh.getInternalObject())
}

func (g BoxGeometry) MergeVertices() {
	g.Object.Call("mergeVertices")
}

func (g BoxGeometry) SortFacesByMaterialIndex() {
	g.Object.Call("sortFacesByMaterialIndex")
}

func (g BoxGeometry) ToJSON() interface{} {
	return g.Object.Call("toJSON")
}

// func (g BoxGeometry) Clone() BoxGeometry {
// 	return g.Object.Call("clone")
// }

func (g BoxGeometry) Copy(source Object3D, recursive bool) *BoxGeometry {
	return &BoxGeometry{Object: g.getInternalObject().Call("copy", source.getInternalObject(), recursive)}
}

func (g BoxGeometry) Dispose() {
	g.Object.Call("dispose")
}

func (g BoxGeometry) getInternalObject() *js.Object {
	return g.Object
}

