package three
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at:
// 2017-08-07 11:59:46.603763777 +0100 BST
//
// using the following cmd:
// ./cmd/object_3d_method_generator -typeName Scene -typeSlug scene

import "github.com/gopherjs/gopherjs/js"
	
func (obj *Scene) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *Scene) Add(m Object3D) {
	obj.Object.Call("add", m.getInternalObject())
}

func (obj *Scene) Copy() *Scene {
	return &Scene{Object: obj.Object.Call("copy")}
}

func (obj *Scene) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *Scene) getInternalObject() *js.Object {
	return obj.Object
}

