package three
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at:
// 2017-08-07 11:59:45.653940345 +0100 BST
//
// using the following cmd:
// ./cmd/object_3d_method_generator -typeName MeshLambertMaterial -typeSlug mesh_lambert_material

import "github.com/gopherjs/gopherjs/js"
	
func (obj *MeshLambertMaterial) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *MeshLambertMaterial) Add(m Object3D) {
	obj.Object.Call("add", m.getInternalObject())
}

func (obj *MeshLambertMaterial) Copy() *MeshLambertMaterial {
	return &MeshLambertMaterial{Object: obj.Object.Call("copy")}
}

func (obj *MeshLambertMaterial) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *MeshLambertMaterial) getInternalObject() *js.Object {
	return obj.Object
}

