package three
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at:
// 2017-08-07 11:59:45.419824353 +0100 BST
//
// using the following cmd:
// ./cmd/object_3d_method_generator -typeName MeshBasicMaterial -typeSlug mesh_basic_material

import "github.com/gopherjs/gopherjs/js"
	
func (obj *MeshBasicMaterial) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *MeshBasicMaterial) Add(m Object3D) {
	obj.Object.Call("add", m.getInternalObject())
}

func (obj *MeshBasicMaterial) Copy() *MeshBasicMaterial {
	return &MeshBasicMaterial{Object: obj.Object.Call("copy")}
}

func (obj *MeshBasicMaterial) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *MeshBasicMaterial) getInternalObject() *js.Object {
	return obj.Object
}

