package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Fog -typeSlug fog

import "github.com/gopherjs/gopherjs/js"
	
func (obj *Fog) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *Fog) Add(m Object3D) {
	obj.Object.Call("add", m.getInternalObject())
}

// func (obj *Fog) Copy() *Fog {
// 	return &Fog{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *Fog) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *Fog) getInternalObject() *js.Object {
	return obj.Object
}

