package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Scene -typeSlug scene

import "github.com/gopherjs/gopherjs/js"
	
func (obj *Scene) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *Scene) Add(m Object3D) {
	obj.Object.Call("add", m.getInternalObject())
}

// func (obj *Scene) Copy() *Scene {
// 	return &Scene{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *Scene) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *Scene) getInternalObject() *js.Object {
	return obj.Object
}

