package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName AmbientLight -typeSlug ambient_light

import "github.com/gopherjs/gopherjs/js"
	
func (obj *AmbientLight) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *AmbientLight) Add(m Object3D) {
	obj.Object.Call("add", m.getInternalObject())
}

// func (obj *AmbientLight) Copy() *AmbientLight {
// 	return &AmbientLight{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *AmbientLight) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *AmbientLight) getInternalObject() *js.Object {
	return obj.Object
}

