package three
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at:
// 2017-08-07 11:59:45.885190249 +0100 BST
//
// using the following cmd:
// ./cmd/object_3d_method_generator -typeName MeshPhongMaterial -typeSlug mesh_phong_material

import "github.com/gopherjs/gopherjs/js"
	
func (obj *MeshPhongMaterial) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *MeshPhongMaterial) Add(m Object3D) {
	obj.Object.Call("add", m.getInternalObject())
}

func (obj *MeshPhongMaterial) Copy() *MeshPhongMaterial {
	return &MeshPhongMaterial{Object: obj.Object.Call("copy")}
}

func (obj *MeshPhongMaterial) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *MeshPhongMaterial) getInternalObject() *js.Object {
	return obj.Object
}

